// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOxWOH9_GiUcz3o-rGWNbjbMz6btZnH4c',
    appId: '1:808869607962:web:0c19cb7027fb07becbefa3',
    messagingSenderId: '808869607962',
    projectId: 'moneymate-efa83',
    authDomain: 'moneymate-efa83.firebaseapp.com',
    storageBucket: 'moneymate-efa83.appspot.com',
    measurementId: 'G-L6M491D9RX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC174sSTmXWX7yXf4XyDNziwZsvHJzTyv0',
    appId: '1:808869607962:android:62416000036d80a1cbefa3',
    messagingSenderId: '808869607962',
    projectId: 'moneymate-efa83',
    storageBucket: 'moneymate-efa83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9e5osXxSlApwG7DDjh6pQXSldzW9OtdM',
    appId: '1:808869607962:ios:114fe520f1ffa475cbefa3',
    messagingSenderId: '808869607962',
    projectId: 'moneymate-efa83',
    storageBucket: 'moneymate-efa83.appspot.com',
    iosBundleId: 'com.example.moneymate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9e5osXxSlApwG7DDjh6pQXSldzW9OtdM',
    appId: '1:808869607962:ios:124161aed25a28f9cbefa3',
    messagingSenderId: '808869607962',
    projectId: 'moneymate-efa83',
    storageBucket: 'moneymate-efa83.appspot.com',
    iosBundleId: 'com.example.moneymate.RunnerTests',
  );
}
